---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/dolt version
    register: dolt_test_output
  - name: dolt version
    debug:
      msg: '{{ dolt_test_output.stdout }}'
